# https://docs.github.com/en/actions/learn-github-actions/variables
name: build-container-activemq-classic

on:
  #push:
  workflow_dispatch:

env:
  PACKER_VERSION: "latest"
  PACKER_CONTEXT: ./builds/docker/activemq-classic

jobs:
  packer:
    runs-on: ubuntu-latest
    name: Run Packer
    steps:
    -
      name: Checkout
      uses: actions/checkout@v3
    -
      name: Setup
      uses: hashicorp/setup-packer@main
      id: setup
      with:
        version: ${{ env.PACKER_VERSION }}
    -
      name: Initialize
      working-directory: ${{ env.PACKER_CONTEXT }}
      id: init
      run: >
        packer init -upgrade .
    -
      name: Validate
      working-directory: ${{ env.PACKER_CONTEXT }}
      id: validate
      run: >
        packer validate .
    -
      name: Build
      working-directory: ${{ env.PACKER_CONTEXT }}
      id: build
      run: >
        packer build -color=false -on-error=abort .
