# https://docs.github.com/en/actions/learn-github-actions/variables
# https://docs.github.com/en/actions/learn-github-actions/contexts
name: build-container-activemq-classic

on:
  #push:
  workflow_dispatch:

env:
  resource_folder: $RUNNER_TEMP
  activemq_version: '6.1.2'
  jdbc_version: '42.7.3'
  hawtio_version: '4.0.0'

jobs:
  packer:
    runs-on: ubuntu-latest
    name: Run Packer
    steps:
    -
      name: Checkout
      uses: actions/checkout@v3
      id: checkout
    -
      name: Setup
      uses: hashicorp/setup-packer@main
      id: setup
      with:
        version: "latest"
    -
      name: Pre-Build
      working-directory: ./builds/docker/activemq-classic # /home/runner/work/packer-image-builds/packer-image-builds/builds/docker/activemq-classic
      id: pre
      run: |
        chmod +rx ./files/*.sh
        ./files/pre-provisioning-activemq.sh
        ./files/pre-provisioning-hawtio.sh
        ./files/pre-provisioning-postgres.sh
    -
      name: Build
      working-directory: ./builds/docker/activemq-classic
      id: build
      run: |
        packer init -upgrade .
        packer validate .
        packer build -color=false -on-error=abort .
      env:
        registry_server: ghcr.io
        repository: ${{ github.repository }}/activemq-classic
        registry_username: ${{ github.actor }}
        registry_password: ${{ github.token }}
