# https://docs.github.com/en/actions/learn-github-actions/variables
# https://docs.github.com/en/actions/learn-github-actions/contexts
name: build-container-payara-server

on:
  workflow_dispatch:

# Shared ENV for all steps/tasks
env: {}

jobs:
  packer:
    runs-on: ubuntu-latest
    name: Run Packer

    strategy:
      matrix:
        payara_version:
        - '6.2024.4'

    steps:
    -
      name: Checkout
      uses: actions/checkout@v3
      id: checkout
    -
      name: Setup
      uses: hashicorp/setup-packer@main
      id: setup
      with:
        version: "latest"
    -
      name: Build
      working-directory: ./builds/docker/payara-server
      id: build
      run: |
        packer init -upgrade .
        packer build -except="push" .
