# https://docs.github.com/en/actions/learn-github-actions/variables
# https://docs.github.com/en/actions/learn-github-actions/contexts
name: build-container-activemq-classic

on:
  #push:
  workflow_dispatch:

# Shared ENV for all steps/tasks
env:
  jdbc_version: '42.7.3'

jobs:
  packer:
    runs-on: ubuntu-latest
    name: Run Packer

    strategy:
      matrix:
        activemq_version:
        - '6.1.2'
        - '5.18.4'

    steps:
    -
      name: Checkout
      uses: actions/checkout@v3
      id: checkout
    -
      name: Setup
      uses: hashicorp/setup-packer@main
      id: setup
      with:
        version: "latest"
    -
      name: Pre-Build # shell-local provisioning fails
      working-directory: ./builds/docker/activemq-classic # /home/runner/work/packer-image-builds/packer-image-builds/builds/docker/activemq-classic
      id: pre
      run: |
        chmod +rx ./files/*.sh
        ./files/pre-provisioning-activemq.sh
        ./files/pre-provisioning-postgres.sh
      env:
        activemq_version: ${{ matrix.activemq_version }}
    -
      name: Build
      working-directory: ./builds/docker/activemq-classic
      id: build
      run: |
        packer init -upgrade .
        packer validate .
        packer build -color=false -on-error=abort .
      env:
        PKR_VAR_activemq_version: ${{ matrix.activemq_version }}
        PKR_VAR_repository: "ghcr.io/${{ github.repository }}/activemq-classic"
        PKR_VAR_registry_server: ghcr.io
        PKR_VAR_registry_username: ${{ github.actor }}
        PKR_VAR_registry_password: ${{ secrets.GITHUB_TOKEN }}
