# https://docs.github.com/en/actions/learn-github-actions/variables
# https://docs.github.com/en/actions/learn-github-actions/contexts
---
name: build-container-activemq-classic

on:
  workflow_dispatch:

# Shared ENV for all steps/tasks
env:
  postgres_jdbc_version: '42.7.3'

jobs:
  packer:
    runs-on: ubuntu-latest
    name: Run Packer

    strategy:
      matrix:
        activemq_version:
        - '6.1.2'
        - '5.18.4'

    steps:
    -
      name: Checkout
      uses: actions/checkout@v3
      id: checkout
    -
      name: Setup
      uses: hashicorp/setup-packer@main
      id: setup
      with:
        version: "latest"
    -
      name: Packer Init
      working-directory: ./builds/container/payara-server
      id: init
      run: |
        packer init -upgrade .
        packer validate .
    -
      name: Packer Build
      working-directory: ./builds/container/activemq-classic
      id: build
      run: |
        packer build .
      env:
        PKR_VAR_registry_server: ghcr.io
        PKR_VAR_registry_username: ${{ github.actor }}
        PKR_VAR_registry_password: ${{ secrets.GITHUB_TOKEN }}
        PKR_VAR_repository: "ghcr.io/${{ github.repository }}/activemq-classic"
        PKR_VAR_jdbc_postgres_version: ${{ env.postgres_jdbc_version }}
        PKR_VAR_activemq_version: ${{ matrix.activemq_version }}
